config/routes.rb
Rails.application.routes.draw do
  resources :music_videos

  resources :documents

  root 'home#index'
  
  resources :posts do
    member do
      get 'upload'
    end
  end
end

app/models/concerns/paginated.rb
module Paginated
  extend ActiveSupport::Concern

  included do
    cattr_accessor :per_page
  end
  
  module ClassMethods
    def total_pages
      (count/per_page).ceil + 1
    end

    def page(page_number=nil)
      page = page_number.nil? ? 1 : page_number.to_i
      limit( per_page ).offset( per_page * (page - 1) )
    end

    def paginated(options={})
      self.per_page = options[:per_page] ? options[:per_page] : 15
    end
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  include Paginated
  
  has_attachment :attachment

  paginated per_page: 50

  default_scope {
    order(created_at: :desc)
  }

  scope :with_attachment, -> {
    where.not(attachment_file: nil)
  }
  
  before_save do
    if attachment_file && attachment_file_changed?
      self.name = attachment_file
    end
  end
end

app/models/music_video.rb
class MusicVideo < ActiveRecord::Base
  include Paginated
 
  @video_styles = [
      {
          name: :thumb,
          format: :jpg,
          suffix: '-00002'
      },
      {
          name: :mp4,
          format: :mp4
      },
      {
          name: :webm,
          format: :webm
      }
  ]

  has_attachment :video, type: :video, styles: @video_styles

  paginated per_page: 30

  default_scope {
    order(created_at: :desc)
  }

  scope :with_video, -> {
    where.not(video_file: nil)
  }

  before_save do
    if video_file && video_file_changed?
      self.title = video_file
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Paginated

  has_attachment :image, type: :image
  
  paginated per_page: 30
  
  default_scope {
    order(created_at: :desc)
  }
  
  scope :with_image, -> {
    where.not(image_file: nil)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:edit, :update, :destroy]

  def index
    @documents = Document.with_attachment.page(params[:page])
    render 'documents/_documents', layout: false if request.xhr?
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.create!(document_params)
    render json: { id: @document.id }
  end

  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_url }
        format.json { render :index, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy
    head :ok
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/music_videos_controller.rb
class MusicVideosController < ApplicationController
  before_action :set_music_video, only: [:show, :edit, :update, :destroy]

  def index
    @music_videos = MusicVideo.with_video.page(params[:page])
    render 'music_videos/_music_videos', layout: false if request.xhr?
  end

  def show
    redirect_to music_videos_path unless @music_video.video.exists?
  end
  
  def edit
  end

  def create
    @music_video = MusicVideo.create!(music_video_params)
    render json: { id: @music_video.id }
  end

  def update
    respond_to do |format|
      if @music_video.update(music_video_params)
        format.html { redirect_to @music_video, notice: 'Music video was successfully updated.' }
        format.json { render :show, status: :ok, location: @music_video }
      else
        format.html { render :edit }
        format.json { render json: @music_video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @music_video.destroy
    head :ok
  end

  private
    def set_music_video
      @music_video = MusicVideo.find(params[:id])
    end

    def music_video_params
      params.require(:music_video).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.with_image.page(params[:page])
    render 'posts/_posts', layout: false if request.xhr?
  end

  def show
    redirect_to posts_path unless @post.image.exists?
  end

  def edit
  end

  def create
    @post = Post.create!(post_params)
    render json: { id: @post.id }
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    head :ok
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/music_videos_helper.rb
module MusicVideosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/documents/_documents.html.erb
<% @documents.each do |document| %>
    <tr>
        <td><%= link_to document.name, document.attachment.url, target: '_blank' %></td>
        <td><%= document.created_at.strftime('%B %-d, %Y - %-I:%M %p')  %></td>
        <td class="text-center">
            <a href="#" data-perform="edit" data-model="document" data-id="<%= document.id %>">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="#" class="text-danger" data-perform="delete" data-model="document" data-id="<%= document.id %>">
                <i class="fa fa-trash-o"></i>
            </a>
        </td>
    </tr>
<% end %>

app/views/documents/edit.html.erb
<div class="container">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4>Post: <%= @document.id %> (<%= @document.name %>)</h4>
        </div>
        <div class="pull-right">
            <div class="btn-group-xs">
                <button class="btn btn-xs btn-primary" data-perform="back">Back</button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <%= render partial: 'stratosphere/attachment_field', locals: { model: @document } %>
    </div>
</div>

app/views/documents/index.html.erb
<div class="container">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4>Documents</h4>
        </div>
        <div class="pull-right">
            <div class="btn-group-xs">
                <button class="btn btn-xs btn-success" data-perform="create" data-model="document">New Document</button>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
                <th>Name</th>
                <th>Date Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody data-paginated="true" data-total-pages="<%= Document.with_attachment.total_pages %>" data-model="document" data-is-paginating="false">
            <%= render 'documents' %>
        </tbody>
    </table>
</div>

app/views/home/index.html.erb
<div class="home-container text-center">
    <div class="social">
        <a href="http://zacharygolba.com" target="_blank"><i class="fa fa-globe"></i></a>
        <a href="https://rubygems.org/gems/stratosphere" target="_blank"><i class="fa fa-diamond"></i></a>
        <a href="https://github.com/zacharygolba/stratosphere" target="_blank"><i class="fa fa-github"></i></a>
    </div>
    <div class="heading">
        <div class="logo-container">
            <i class="logo fa fa-fw fa-cloud-upload"></i>
        </div>
        <code>gem 'stratosphere'</code>
        <h1>stratosphere</h1>
        <h4>attachments in the cloud</h4>
    </div>
    <div class="container examples">
        <div class="row">
            <div class="col-sm-4 text-center">
                <%= link_to documents_path do %>
                    <div class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-file-pdf-o fa-stack-1x fa-inverse"></i>
                    </div>
                    <h5>Basic Attachments</h5>
                <% end %>
            </div>
            <div class="col-sm-4 text-center">
                <%= link_to posts_path do %>
                    <div class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-file-image-o fa-stack-1x fa-inverse"></i>
                    </div>
                    <h5>Image Attachments</h5>
                <% end %>
            </div>
            <div class="col-sm-4 text-center">
                <%= link_to music_videos_path do %>
                    <div class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-file-video-o fa-stack-1x fa-inverse"></i>
                    </div>
                    <h5>Video Attachments</h5>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Stratosphere | Attachments in the cloud</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= analytics_init if Rails.env.production? %>
    <%= csrf_meta_tags %>
</head>
<body data-controller-name="<%= controller_name %>" data-controller-action="<%= action_name %>">
<%= render partial: 'shared/navbar' unless controller_name == 'home' %>
<%= yield %>
<%= render partial: 'shared/footer' %>
</body>
</html>

app/views/music_videos/_music_videos.html.erb
<% @music_videos.each do |music_video| %>
    <div class="col-sm-4 image-container">
        <%= link_to music_video_path(music_video) do %>
            <%= image_tag music_video.video.url(:thumb), class: 'img-responsive' %>
        <% end %>
    </div>
<% end %>

app/views/music_videos/edit.html.erb
<div class="container">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4>Music Video: <%= @music_video.id %></h4>
        </div>
        <div class="pull-right">
            <div class="btn-group btn-group-xs">
                <button type="button" class="btn btn-primary" data-perform="back">Back</button>
                <button type="button" class="btn btn-primary" data-perform="delete" data-model="music_video" data-id="<%= @music_video.id %>">Delete</button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <%= render partial: 'stratosphere/attachment_field', locals: { model: @music_video } %>
    </div>
</div>

app/views/music_videos/index.html.erb
<div class="container" data-paginated="true" data-total-pages="<%= MusicVideo.with_video.total_pages %>" data-model="music_video" data-is-paginating="false" data-has-rows="true">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4>Music Videos</h4>
        </div>
        <div class="pull-right">
            <div class="btn-group-xs">
                <button class="btn btn-xs btn-success" data-perform="create" data-model="music_video">New Music Video</button>
            </div>
        </div>
    </div>
    <% @music_videos.each_slice(3) do |row| %>
        <div class="row">
            <% row.each do |music_video| %>
                <div class="col-sm-4 image-container">
                    <%= link_to music_video_path(music_video) do %>
                        <%= image_tag music_video.video.url(:thumb), class: 'img-responsive' %>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/music_videos/show.html.erb
<div class="container">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4><%= @music_video.video.file_name %></h4>
        </div>
        <div class="pull-right">
            <div class="btn-group btn-group-xs">
                <button class="btn btn-primary" data-perform="back">Back</button>
                <button class="btn btn-primary" data-perform="edit" data-model="music_video" data-id="<%= @music_video.id %>">Edit</button>
                <button class="btn btn-primary" data-perform="delete" data-model="music_video" data-id="<%= @music_video.id %>">Delete</button>
            </div>
        </div>
    </div>
    <video class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" poster="<%= @music_video.video.url(:thumb) %>">
        <source src="<%= @music_video.video.url(:mp4) %>" type="video/mp4">
        <source src="<%= @music_video.video.url(:webm) %>" type="video/webm">
    </video>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <div class="col-sm-4 image-container">
        <%= link_to post_path(post) do %>
            <%= image_tag post.image.url, class: 'img-responsive' %>
        <% end %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <%= form_for @post do |f| %>
        <div class="content-heading clearfix">
            <div class="pull-left">
                <h4>Post: <%= @post.id %> (<%= @post.title %>)</h4>
            </div>
            <div class="pull-right">
                <div class="btn-group btn-group-xs">
                    <button type="button" class="btn btn-primary" data-perform="back">Back</button>
                    <button type="button" class="btn btn-primary" data-perform="delete" data-model="post" data-id="<%= @post.id %>">Delete</button>
                    <%= button_tag 'Save', type: 'submit', class: 'btn btn-primary' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :title, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control', placeholder: 'New Post' %>
        </div>
        <div class="form-group">
            <%= render partial: 'stratosphere/attachment_field', locals: { model: @post } %>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container" data-paginated="true" data-total-pages="<%= Post.with_image.total_pages %>" data-model="post" data-is-paginating="false" data-has-rows="true">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4>Posts</h4>
        </div>
        <div class="pull-right">
            <div class="btn-group-xs">
                <button class="btn btn-xs btn-success" data-perform="create" data-model="post">New Post</button>
            </div>
        </div>
    </div>
    <% @posts.each_slice(3) do |row| %>
        <div class="row">
            <% row.each do |post| %>
                <div class="col-sm-4 image-container">
                    <%= link_to post_path(post) do %>
                        <%= image_tag post.image.url, class: 'img-responsive' %>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="content-heading clearfix">
        <div class="pull-left">
            <h4><%= @post.title %></h4>
        </div>
        <div class="pull-right">
            <div class="btn-group btn-group-xs">
                <button class="btn btn-primary" data-perform="back">Back</button>
                <button class="btn btn-primary" data-perform="edit" data-model="post" data-id="<%= @post.id %>">Edit</button>
                <button class="btn btn-primary" data-perform="delete" data-model="post" data-id="<%= @post.id %>">Delete</button>
            </div>
        </div>
    </div>
    <%= image_tag @post.image.url, alt: @post.title, class: 'img-responsive post-img' %>
</div>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer text-center fixed">
    <div class="container">
        <ul>
            <li>
                &copy; Copyright 2015 - <a href="http://zacharygolba.com" target="_blank">Zachary Golba</a>
            </li>
            <li>
                <a href="https://github.com/zacharygolba/stratosphere" target="_blank">Source</a>
            </li>
            <li>
                <a href="https://rubygems.org/gems/stratosphere" target="_blank">Gem</a>
            </li>
            <li>
                <a href="http://www.rubydoc.info/gems/stratosphere/0.0.1" target="_blank">
                    Doc<span class="visible-inline-xs">s</span><span class="hidden-inline-xs">umentation</span>
                </a>
            </li>
            <li>
                <a href="https://github.com/zacharygolba/stratosphere/issues" target="_blank"><span class="hidden-inline-xs">Report a </span> Bug<span class="visible-inline-xs">s</span> </a>
            </li>
        </ul>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<header id="navbar" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: 'navbar-brand' do %>
                <i class="fa fa-cloud-upload"></i>
                <span>stratosphere</span>
            <% end %>
        </div>
        <div id="main-navigation" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Basic Attachments', documents_path, data: { route: 'documents-index' } %></li>
                <li><%= link_to 'Image Attachments', posts_path, data: { route: 'posts-index' } %></li>
                <li><%= link_to 'Video Attachments', music_videos_path, data: { route: 'music_videos-index' } %></li>
            </ul>
        </div>
    </div>
</header>

app/views/stratosphere/_attachment_field.html.erb
<% attachment = model.send(model.class.attachment_name) %>
<div class="stratosphere-container" data-stratosphere-enabled="true" data-stratosphere-container-type="field" data-model-name="<%= model.class.to_s.underscore.pluralize %>" data-model-id="<%= model.id %>" data-attachment-name="<%= model.class.attachment_name.to_s %>">
    <label class="statosphere-uploader-label">
        <%= model.class.attachment_name.to_s.capitalize %>
    </label>
    <div class="upload-controls">
        <div class="current-attachment" style="display: <%= (attachment.exists? || attachment.has_default?) ? 'inline-block' : 'none' %>; margin-right: 5px;">
            <% if attachment.type == :image %>
                <%= image_tag attachment.url, width: 32, height: 32, style: 'display: inline-block;' %>
                <%= link_to attachment.file_name, attachment.url, target: '_blank', class: 'file-name', style: 'margin-left: 5px;' %>
            <% elsif attachment.type == :video %>
                <div>
                    <video class="video-js vjs-default-skin vjs-big-play-centered" preload="auto" poster="<%= attachment.url(:thumb) %>" controls>
                        <source src="<%= attachment.url(:mp4) %>" type="video/mp4">
                        <source src="<%= attachment.url(:webm) %>" type="video/webm">
                    </video>
                </div>
                <%= link_to attachment.file_name, attachment.url, target: '_blank', class: 'file-name', style: 'margin-left: 5px;' %>
            <% else %>
                <%= link_to attachment.file_name, attachment.url, target: '_blank', class: 'file-name' %>
            <% end %>
        </div>
        <div class="actions" style="display: inline-block;">
            <div class="upload-container" style="position: relative; display: inline-block;">
                <% if attachment.type == :image %>
                    <input type="file" accept="image/*" style="position: absolute; opacity: 0; pointer-events: none;">
                <% elsif attachment.type == :video %>
                    <input type="file" accept="video/*" style="position: absolute; opacity: 0; pointer-events: none;">
                <% else %>
                    <input type="file" accept="*/*" style="position: absolute; opacity: 0; pointer-events: none;">
                <% end %>
                <button class="btn btn-xs btn-primary" data-stratosphere-action="upload">Upload</button>
            </div>
            <button class="btn btn-xs btn-danger" data-stratosphere-action="delete" style="display: <%= attachment.exists? ? 'initial' : 'none' %>; margin-left: 3px;">Delete</button>
        </div>
    </div>
    <div class="upload-progress" style="display: none;">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0;">
            </div>
        </div>
    </div>
</div>